### ISSUE TITLE
Add css class to li in pager

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#547]
Changes in bootstrap 4 alpha 6, `.pager` css class is removed.

 http://v4-alpha.getbootstrap.com/components/pagination/

```
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</nav>
```

How can I specify `page-item` class on the `<li>` for the Pager and PagerSlim shapes?

**Comment by stevetayloruk** [comment]
Cant seem to create a Pager.cshtml alternate too. It seems that if a PagerId is not supplied, then it doesn't create any alternates.

**Comment by agriffard** [comment]
At least, I can do this in my `ListPart-Blog.cshtml` view :

```
@{ 
    Model.Pager.Classes.Add("blog-pagination");
    Model.Pager.PreviousText = T["Older"];
    Model.Pager.NextText = T["Newer"];
    Model.Pager.PreviousClass = "btn btn-outline-primary";
    Model.Pager.NextClass = "btn btn-outline-secondary";
}
@await DisplayAsync(Model.Pager)
```

**Comment by sebastienros** [comment]
I will add these classes by default then, but otherwise because a Pager morphes to a List shape you can do 
`Model.Pager.ItemClasses.Add("page-item")`

**Comment by sebastienros** [comment]
Fixed with this commit https://github.com/OrchardCMS/Orchard2/commit/5730a221c442524c80a024f235a83a96d4319882

**Comment by sebastienros** [comment]
I am keeping the current classes (pager) as the css will automatically extend the one for boostrap, it hasn't changed apparently.

I added the documentation to answer your questions, if it's not clear then let me know.

**Comment by stevetayloruk** [comment]
Thanks @sebastienros for looking at this, but I still can't seem to customise the PagerSlim that gets used by the ListPart.  

When I add an alternate such as `Pager.Previous.cshtml` I get the following error:

```ArgumentException: An item with the same key has already been added. Key: pager_previous```

When adding a PagerId such as `Pager-MainBlog.Previous.cshtml` it doesn't pick it up.

Ultimately, I would like to change the HTML markup considerably, such as adding wrappers and using DIV's instead of ListItems.

Thanks

Steve

**Comment by sebastienros** [comment]
Have you tried `PagerSlim-MainBlog.Previous` ?

**Comment by stevetayloruk** [comment]
Yes, I did try that but still no good.

thanks

**Comment by sebastienros** [comment]
In `ListPart-Blog.cshtml` I did 

` Model.Pager.PagerId = "Blog";`

Then I created `Pager-Blog.Previous.cshtml` and it worked fine.

**Comment by stevetayloruk** [comment]
Ha, this does work. I was confused based on the terminology that was outputted and thought "Previous" would be for Older Posts but in fact "Next" is for older posts and "Previous" is for newer posts.

Thanks!

**Comment by sebastienros** [comment]
I get it, on the first page you see only one link so if you use the wrong one you think it doesn't work ;)

**Comment by stevetayloruk** [comment]
yep, _facepalm_.

But the issue still remains with the Pager itself to be overridden. But there is no rush on that I think you have created another issue for it. 

thanks

**Comment by sebastienros** [comment]
Not aware of another issue, please point me to it.

Also even though this is super flexible, this is super not obvious ;) And without this piece of code https://github.com/OrchardCMS/Orchard2/blob/master/src/Orchard.Cms.Web/Modules/Orchard.Navigation/PagerShapes.cs#L411 you can't even know how to get the url in order to render the link.

So I think I will provide a Url property on the pager link elements so it can be used directly. And also document it better with an example based on what people actually do with pager:
- change classes for the `<ul>`, `<li>` or `<a>`
- change the html for `<a>`

Should I show how to change the HTML for the full pager? That might be simpler for designer to have to rewrite the full html rendering logic than trying to understand how to find the correct template name and property for just changing a class in the pager.

**Comment by stevetayloruk** [comment]
Here is the other issue: #571 

Yeah, a URL property would be useful. Currently, I'm replicated the behaviour:

```@using Microsoft.AspNetCore.Routing

@{
    var RouteValues = (object)((dynamic)Model).RouteValues;
    RouteValueDictionary rvd;

    if (RouteValues == null)
    {
        rvd = new RouteValueDictionary();
    }
    else
    {
        rvd = RouteValues as RouteValueDictionary ?? new RouteValueDictionary(RouteValues);
    }

    var route = Url.Action(rvd["action"].ToString(), rvd["controller"].ToString(), rvd as RouteValueDictionary);
}
<div class="nav-next"><a href="@route">@Model.Value <span><i class="fa fa-arrow-circle-o-right"></i></span></a></div>```

Any examples of the full pager would be useful. Thanks

**Comment by sebastienros** [comment]
This issue, ok.
